version: 1.2.{build}
image: WMF 5

environment:
  NEXOSIS_API_KEY:
    secure: Vu9ZUtpEcQ/EoKx71vLot16ynFoMm0Tta7rR2FHUJlUEula3TAlnL0cl8BLubSvo
  NEXOSIS_BASE_TEST_URL: https://api.uat.nexosisdev.com/v1
  NugetApiKey:
    secure: ZVnyY36pyop4d/d/NqbJh9NDjouFQpPxX8BcIjO+Zv7zhn8kaTbS7soALfJ0MKSD

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

build: false

install:
- ps: >-
    Get-PackageProvider -Name NuGet -ForceBootstrap | Out-Null

    Install-Module -Name InvokeBuild -Force

    Install-Module -Name Pester -Force

    Install-Module -Name PSScriptAnalyzer -Force

    Install-Module -Name BuildHelpers -Force

    Install-Module -Name PSDeploy -Force

before_test:
- ps: >-
    pushd PSNexosisClient

    Invoke-Build Clean
    
    Invoke-Build Build

    Invoke-Build Analyze

    popd

test_script:
- ps: >-
    pushd PSNexosisClient

    Invoke-Build RunUnitTests

    Invoke-Build ConfirmTestsPassed

    Set-BuildEnvironment

    Invoke-PSDeploy -Path .\Deploy.psdeploy.ps1 -Force
    
    popd