Function Get-NexosisContest {
<# 
 .Synopsis
  Gets detailed data science information generated by a session.

 .Description
  During the execution of a session, many different algorithms can be run, in order to see which algorithm produces
  the best results. The contest information returned from this endpoint contains details about all of the algorithms
  that were attempted, which one is the champion, and various scoring metrics which were used to determine the best
  algorithm. 
  
  Note: This endpoint is not available under the community plan. Please upgrade to a paid plan if you are
  currently on Community. Be sure to use the Paid Subscription key if you have already upgraded.

 .Parameter SessionId
  A Session identifier (UUID) of the session contest contestants to retrieve.

 .Example
  # Return just the contestants from the contest run for the given serssion
  Get-NexosisContest -SessionId 015df24f-7f43-4efe-b8ba-1e28d67eb3fa

#>[CmdletBinding()]
	Param(
        [Parameter(Mandatory=$true, ValueFromPipeline=$True)]
        [GUID]$SessionId
	)
    process {
        $encodedSessionId = [uri]::EscapeDataString($SessionId)
        Invoke-Http -method Get -path "sessions/$encodedSessionId/contest"
    }
}